CityByte/urls.py
from django.contrib import admin
from django.urls import path, include
from search.views import main_page
from info.views import info_page, profile_page, addTofav
from .views import SignUpView
from apps.accounts.views import signup
from apps.accounts.views import signup, CustomLoginView
from . import views
urlpatterns = [
    path("", main_page, name="main_page"),
    path("accounts/signup/", signup, name="signup"),
    path("accounts/login/", CustomLoginView.as_view(), name="login"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("profile/", profile_page, name="profile_page"),
    path("city", info_page, name="info_page"),
    path("admin/", admin.site.urls),
    path(
        "api/search/", include(("search.urls", "search"), namespace="search")
    ),
    path("api/info/", include(("info.urls", "info"), namespace="info")),
    path("api/addToFav/", addTofav, name="addToFav"),
    path('city/<str:city_name>/', views.city_info, name='city_info'),
    path('city/<str:city>/<str:country>/news/', views.city_news, name='city_news'),
    # path('city/<str:city>/news/', views.city_news, name='city_news'),
]

info/urls.py
from django.urls import path
from info.views import place_photo

urlpatterns = [
    path("place/photo", place_photo, name="place_photo"),
]

search/urls.py
from django.urls import path

from .views import city_suggestions, city_photo

urlpatterns = [
    path("city", city_suggestions, name="city_search"),
    path("city/photo", city_photo, name="city_photo"),
]

search/views.py
# from django.conf import settings
# from django.http import JsonResponse
# from django.shortcuts import render
# from django.views.decorators.http import require_http_methods
 
# from search.helpers.autocomplete import GenericDBSearchAutoCompleteHelper
# from search.helpers.photo import UnplashCityPhotoHelper
# from search.utils.search import AmadeusCitySearch
# from search.utils.url import URL
# from django.contrib.auth.decorators import login_required
# from django.contrib.auth import get_user_model
from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.http import require_http_methods
 
from search.helpers.autocomplete import GenericDBSearchAutoCompleteHelper
from search.helpers.photo import UnplashCityPhotoHelper
from search.utils.search import AmadeusCitySearch
from search.utils.url import URL
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib.auth.views import PasswordResetView
from django.shortcuts import render
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain
 
@login_required
@require_http_methods(["GET"])
def main_page(request):
    user_count = get_user_model().objects.all().count()
    return render(request, "search/search.html", context={"request": request, "userCount": user_count})
 
 
@require_http_methods(["GET"])
def city_suggestions(request):
    suggestions_data = GenericDBSearchAutoCompleteHelper(
        klass=AmadeusCitySearch, url=URL(**settings.AMADEUS_CONFIG)
    ).get_suggestions(city=request.GET.get("q"), max=10)
 
    return JsonResponse({"results": suggestions_data.get("data", [])})
 
 
@require_http_methods(["GET"])
def city_photo(request):
    photo_link = UnplashCityPhotoHelper().get_city_photo(
        city=request.GET.get("q")
    )
    return JsonResponse(
        {
            "path": photo_link,
        }
    )


def initialize_gemini_llm():
    api_key = 'AIzaSyCQuxhdViKd_-H1CQxEpFsgsHEolKLEN7w' # Fetch the key from an environment variable
    if not api_key:
        raise Exception("Gemini API Key not set. Please configure the key.")
    
    # Set up the Gemini LLM
    my_llm = ChatGoogleGenerativeAI(model='gemini-pro', api_key=api_key)
    return my_llm

def city_info(request, city_name):
    itinerary = None  # To store the generated itinerary
    if request.method == 'POST':
        # Get the number of days from the form input
        days = request.POST.get('days')

        # Initialize Gemini LLM
        my_llm = initialize_gemini_llm()

        # Create a prompt template with placeholders for the city and number of days
        my_prompt = PromptTemplate.from_template('Create an itinerary for {placename} for {num} days')
        
        # Create the chain
        chain = LLMChain(llm=my_llm, prompt=my_prompt, verbose=False)
        
        # Define both place and num
        inputs = {'placename': city_name, 'num': days}
        
        # Invoke the chain with both inputs
        response = chain.invoke(input=inputs)
        
        # Get the response text from the LLM
        itinerary = response

        # Render the new itinerary page with the generated HTML
        return render(request, 'info/itinerary.html', {
            'city': city_name,
            'itinerary': itinerary
        })

templates/search/search.html
{% extends '../base.html' %}
 
{% block title %}Search{% endblock %}
 
 
{% block content %}
 
<style>
    .container {
        margin: auto;
    }
 
    .search-box-container{
        display: flex;
        flex-direction: column;
        position: relative;
    }
 
    /* .search-box, .search-box-suggestion {
        position: absolute;
        top: 10vh;
        border: none;
    } */
    .auto-complete-container{
        position: absolute;
        top: 15;
    }
 
    .search-box-suggestion {
        overflow: hidden;
    }
 
    #query, #suggestion, #suggestion-before, #suggestion-after {
        /*position: absolute;*/
        font-size: 10rem;
        color: #f5f9e9;
        border: none;
    }
 
    #suggestion, #suggestion-before, #suggestion-after {
        /*overflow: hidden;*/
 
        z-index: 1;
    }
 
    #query {
        background: transparent;
 
        padding: 0;
 
        color: white;
        border-color: inherit;
        -webkit-box-shadow: none;
        box-shadow: none;
        caret-color: transparent;
 
        z-index: 2;
    }
    .d-block{
        display: block;
        color: "blue";
    }
 
    .d-none{
        display: none;
    }
 
    #loading{
        background: rgba(0,0,0,0.2);
        color: white; margin: 8px 0; padding: 2px 8px; cursor: pointer;
 
    }
 
    .auto-complete-li{
        background: rgba(0,0,0,0.2);
        color: white; margin: 8px 0; padding: 2px 8px; cursor: pointer;
    }
 
    .auto-complete-li:hover{
        background: rgba(0,0,0,0.5);
 
    }
</style>
 
 
<div class="container">
    <h1 style="font-size: 1rem; color: white; text-align: center; position:absolute; bottom:0; left:0; right:0;">{{userCount}} <span class="fa fa-regular fa-user fav"></span> signed up till now!</h1>
    <div class="search-box-container">
        <div class="search-box"><input type="text" class="form-control" id="query" spellcheck="false" autocomplete="off" onkeyup="getSuggestions(event)" placeholder="Type a city"></div>
        <div class="d-none" id="loading">
            Loading...
        </div>
        <div id="auto-complete-container" style="font-size:24px; height: 150px; overflow-y: hidden;">
            <ul id="auto-complete-ul" style="list-style-type: none;">
 
            </ul>
        </div>
 
    </div>
</div>
 
 
<script>
    var timeout = null;
    var timeout1 = null;
    load = document.getElementById("loading")
    auto_complete_list = document.getElementById("auto-complete-ul")
    lists = []
 
    function reflectSuggestions(city, citiesJSON) {
        let citySuggestions = JSON.parse(citiesJSON).results;
 
        if (citySuggestions.length !== 0) {
            let cityFirstSuggestion = citySuggestions[0].name;
 
            clearTimeout(timeout1);
            timeout1 = setTimeout(getCityPhoto, 100, cityFirstSuggestion, updateBackground);
 
            // document.getElementById('suggestion-before').innerHTML = cityFirstSuggestion.slice(0, cityFirstSuggestion.indexOf(city));
            // document.getElementById('suggestion-after').innerHTML = cityFirstSuggestion.slice(cityFirstSuggestion.indexOf(city) + city.length);
        }
    }
 
    function updateBackground(pathJSON) {
        let path = JSON.parse(pathJSON).path;
 
        if (path != null) {
            document.body.style.background = null;
            document.body.style.backgroundImage = "url('" + path + "')";
            document.body.style.backgroundSize = "cover";
            document.body.style.backgroundRepeat = "no-repeat";
        }
    }
 
    function getCityPhoto(city, callback1) {
        let xhr1 = new XMLHttpRequest();
        let url1 = new URL('{{ request.scheme }}://{{ request.get_host }}{% url 'search:city_photo' %}');
        url1.searchParams.set('q', city);
 
        xhr1.onload = function(e) {
            callback1(this.responseText);
        }
 
        xhr1.open('GET', url1, true);
        xhr1.send();
    }
 
    function getCityList(callback) {
        console.log(load.classList)
 
        load.classList.remove("d-none")
        load.classList.add("d-block")
 
        console.log(load.classList)
        let xhr = new XMLHttpRequest();
        let city = document.getElementById("query").value;
 
        if (city.length === 0) {
            load.classList.add("d-none")
            load.classList.remove("d-block")
 
            return;
        }
 
        let url = new URL('{{ request.scheme }}://{{ request.get_host }}{% url 'search:city_search' %}');
        url.searchParams.set('q', city);
 
        xhr.onload = function(e) {
            console.log(this.responseText)
 
            var res = JSON.parse(this.responseText).results
            lists = []
            li_content = ""
            for(var item of res){
                lists.push(item)
                let cityLabel = `${item.name},${item.address.countryCode}`
                li_content += `<li class="auto-complete-li" onClick='updateQuery(event)'>${cityLabel}</li>`
            }
            auto_complete_list.innerHTML = li_content
            console.log(lists)
            if(lists.length == 0 && document.getElementById("query").value !== ""){
                console.log("City Not found!");
                alert("City Not Found! Try a different city!")
 
            }
            callback(city, this.responseText);
            load.classList.add("d-none")
            load.classList.remove("d-block")
        }
 
        xhr.open('GET', url, true);
        xhr.send();
 
    }
 
    function updateQuery(event){
        console.log(event.target.innerHTML)
        document.getElementById("query").value = event.target.innerHTML.split(',')[0]
        clearTimeout(timeout);
        timeout = setTimeout(getCityList, 700, reflectSuggestions);
        auto_complete_list.innerHTML = ""
        let place_name = event.target.innerHTML.split(',')
        for(var x of lists){
            console.log(x)
            console.log(place_name)
            if(x.name === place_name[0] && x.address.countryCode === place_name[1]){
                location.href = "{% url "info_page" %}?city=" + x.name + "&country=" + x.address.countryCode;
 
                break;
            }
        }
 
    }
 
    function redict_to_info(city, citiesJSON) {
        let citySuggestions = JSON.parse(citiesJSON).results;
 
        if (citySuggestions.length !== 0) {
            location.href = "{% url "info_page" %}?city=" + citySuggestions[0].name + "&country=" + citySuggestions[0].address.countryCode;
        }
    }
 
    function clearSuggestions() {
        load.classList.add("d-none")
        load.classList.remove("d-block")
        // document.getElementById('suggestion-before').innerHTML = "";
        // document.getElementById('suggestion-after').innerHTML = "";
        document.body.style.backgroundImage = null;
        document.body.style.background = "#3F3F3F";
        document.body.style.backgroundSize = null;
        document.body.style.backgroundRepeat = null;
    }
 
    function getSuggestions(e){
        if (e.key === 'Enter' || e.keyCode === 13) {
            getCityList(redict_to_info);
        }
        auto_complete_list.innerHTML = ""
        load.classList.add("d-none")
        load.classList.remove("d-block")
        document.getElementById("query").value = document.getElementById("query").value.split(' ').map(s => s.charAt(0).toUpperCase() + s.slice(1)).join(' ');
        document.getElementById('query').innerHTML =  '<b>' + document.getElementById("query").value + '</b>';
        clearSuggestions();
 
        clearTimeout(timeout);
        timeout = setTimeout(getCityList, 700, reflectSuggestions);
    }
 
    setTimeout(getSuggestions, 1000);
</script>
 
{% endblock %}

templates/search/search_old.html
{% extends '../base.html' %}
 
{% block title %}Search{% endblock %}
 
 
{% block content %}
 
<style>
    .container {
        margin: auto;
    }
 
    .search-box-container{
        display: flex;
        flex-direction: column;
        position: relative;
    }
 
    /* .search-box, .search-box-suggestion {
        position: absolute;
        top: 10vh;
        border: none;
    } */
    .auto-complete-container{
        position: absolute;
        top: 15;
    }
 
    .search-box-suggestion {
        overflow: hidden;
    }
 
    #query, #suggestion, #suggestion-before, #suggestion-after {
        /*position: absolute;*/
        font-size: 10rem;
        color: #f5f9e9;
        border: none;
    }
 
    #suggestion, #suggestion-before, #suggestion-after {
        /*overflow: hidden;*/
 
        z-index: 1;
    }
 
    #query {
        background: transparent;
 
        padding: 0;
 
        color: white;
        border-color: inherit;
        -webkit-box-shadow: none;
        box-shadow: none;
        caret-color: transparent;
 
        z-index: 2;
    }
    .d-block{
        display: block;
        color: "blue";
    }
 
    .d-none{
        display: none;
    }
 
    #loading{
        background: rgba(0,0,0,0.2);
        color: white; margin: 8px 0; padding: 2px 8px; cursor: pointer;
 
    }
 
    .auto-complete-li{
        background: rgba(0,0,0,0.2);
        color: white; margin: 8px 0; padding: 2px 8px; cursor: pointer;
    }
 
    .auto-complete-li:hover{
        background: rgba(0,0,0,0.5);
 
    }
</style>
 
 
<div class="container">
    <h1 style="font-size: 1rem; color: white; text-align: center; position:absolute; bottom:0; left:0; right:0;">{{userCount}} <span class="fa fa-regular fa-user fav"></span> signed up till now!</h1>
    <div class="search-box-container">
        <div class="search-box"><input type="text" class="form-control" id="query" spellcheck="false" autocomplete="off" onkeyup="getSuggestions(event)" placeholder="Type a city"></div>
        <div class="d-none" id="loading">
            Loading...
        </div>
        <div id="auto-complete-container" style="font-size:24px; height: 150px; overflow-y: hidden;">
            <ul id="auto-complete-ul" style="list-style-type: none;">
 
            </ul>
        </div>
 
    </div>
</div>
 
 
<script>
    var timeout = null;
    var timeout1 = null;
    load = document.getElementById("loading")
    auto_complete_list = document.getElementById("auto-complete-ul")
    lists = []
 
    function reflectSuggestions(city, citiesJSON) {
        let citySuggestions = JSON.parse(citiesJSON).results;
 
        if (citySuggestions.length !== 0) {
            let cityFirstSuggestion = citySuggestions[0].name;
 
            clearTimeout(timeout1);
            timeout1 = setTimeout(getCityPhoto, 100, cityFirstSuggestion, updateBackground);
 
            // document.getElementById('suggestion-before').innerHTML = cityFirstSuggestion.slice(0, cityFirstSuggestion.indexOf(city));
            // document.getElementById('suggestion-after').innerHTML = cityFirstSuggestion.slice(cityFirstSuggestion.indexOf(city) + city.length);
        }
    }
 
    function updateBackground(pathJSON) {
        let path = JSON.parse(pathJSON).path;
 
        if (path != null) {
            document.body.style.background = null;
            document.body.style.backgroundImage = "url('" + path + "')";
            document.body.style.backgroundSize = "cover";
            document.body.style.backgroundRepeat = "no-repeat";
        }
    }
 
    function getCityPhoto(city, callback1) {
        let xhr1 = new XMLHttpRequest();
        let url1 = new URL('{{ request.scheme }}://{{ request.get_host }}{% url 'search:city_photo' %}');
        url1.searchParams.set('q', city);
 
        xhr1.onload = function(e) {
            callback1(this.responseText);
        }
 
        xhr1.open('GET', url1, true);
        xhr1.send();
    }
 
    function getCityList(callback) {
        console.log(load.classList)
 
        load.classList.remove("d-none")
        load.classList.add("d-block")
 
        console.log(load.classList)
        let xhr = new XMLHttpRequest();
        let city = document.getElementById("query").value;
 
        if (city.length === 0) {
            load.classList.add("d-none")
            load.classList.remove("d-block")
 
            return;
        }
 
        let url = new URL('{{ request.scheme }}://{{ request.get_host }}{% url 'search:city_search' %}');
        url.searchParams.set('q', city);
 
        xhr.onload = function(e) {
            console.log(this.responseText)
 
            var res = JSON.parse(this.responseText).results
            lists = []
            li_content = ""
            for(var item of res){
                lists.push(item)
                let cityLabel = `${item.name},${item.address.countryCode}`
                li_content += `<li class="auto-complete-li" onClick='updateQuery(event)'>${cityLabel}</li>`
            }
            auto_complete_list.innerHTML = li_content
            console.log(lists)
            if(lists.length == 0 && document.getElementById("query").value !== ""){
                console.log("City Not found!");
                alert("City Not Found! Try a different city!")
 
            }
            callback(city, this.responseText);
            load.classList.add("d-none")
            load.classList.remove("d-block")
        }
 
        xhr.open('GET', url, true);
        xhr.send();
 
    }
 
    function updateQuery(event){
        console.log(event.target.innerHTML)
        document.getElementById("query").value = event.target.innerHTML.split(',')[0]
        clearTimeout(timeout);
        timeout = setTimeout(getCityList, 700, reflectSuggestions);
        auto_complete_list.innerHTML = ""
        let place_name = event.target.innerHTML.split(',')
        for(var x of lists){
            console.log(x)
            console.log(place_name)
            if(x.name === place_name[0] && x.address.countryCode === place_name[1]){
                location.href = "{% url "info_page" %}?city=" + x.name + "&country=" + x.address.countryCode;
 
                break;
            }
        }
 
    }
 
    function redict_to_info(city, citiesJSON) {
        let citySuggestions = JSON.parse(citiesJSON).results;
 
        if (citySuggestions.length !== 0) {
            location.href = "{% url "info_page" %}?city=" + citySuggestions[0].name + "&country=" + citySuggestions[0].address.countryCode;
        }
    }
 
    function clearSuggestions() {
        load.classList.add("d-none")
        load.classList.remove("d-block")
        // document.getElementById('suggestion-before').innerHTML = "";
        // document.getElementById('suggestion-after').innerHTML = "";
        document.body.style.backgroundImage = null;
        document.body.style.background = "#3F3F3F";
        document.body.style.backgroundSize = null;
        document.body.style.backgroundRepeat = null;
    }
 
    function getSuggestions(e){
        if (e.key === 'Enter' || e.keyCode === 13) {
            getCityList(redict_to_info);
        }
        auto_complete_list.innerHTML = ""
        load.classList.add("d-none")
        load.classList.remove("d-block")
        document.getElementById("query").value = document.getElementById("query").value.split(' ').map(s => s.charAt(0).toUpperCase() + s.slice(1)).join(' ');
        document.getElementById('query').innerHTML =  '<b>' + document.getElementById("query").value + '</b>';
        clearSuggestions();
 
        clearTimeout(timeout);
        timeout = setTimeout(getCityList, 700, reflectSuggestions);
    }
 
    setTimeout(getSuggestions, 1000);
</script>
 
{% endblock %}